# Generated by Django 5.2.16 on 2026-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0006_webhookevent_alter_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("daily", "One Day"),
                    ("weekly", "One Week"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
    ]
