# Generated by Django 5.2.16 on 2026-09-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0007_membership_plan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
