# Generated by Django 5.2.16 on 2026-09-14 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0008_membership_is_premium"),
    ]

    operations = [
        migrations.CreateModel(
            name="DurationDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_months",
                    models.PositiveSmallIntegerField(
                        help_text="Minimum months for this discount to apply (e.g. 2 = applies from 2 months onward).",
                        unique=True,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage discount per month (e.g. 2 means each month's price is reduced by 2%).",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("min_months",),
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
    ]
