# Generated by Django 5.2.16 on 2026-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0012_manual_payment_and_payment_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsettings",
            name="bank_account_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="paymentsettings",
            name="bank_ifsc",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="paymentsettings",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
