# Generated by Django 5.2.16 on 2026-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0013_paymentsettings_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_renewal",
            field=models.BooleanField(default=False),
        ),
    ]
