# Generated by Django 5.2.16 on 2026-09-18 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0014_membership_is_renewal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Case-insensitive. Uppercased automatically on save.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed amount")],
                        default="percent",
                        help_text="Percentage (%) of the plan total, or a flat amount (₹) off.",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount for this coupon: a % (e.g. 10 = 10% off) or a flat ₹ amount.",
                        max_digits=6,
                    ),
                ),
                (
                    "min_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Minimum plan total (before coupon) required. 0 = any amount.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hard cap on the discount this coupon can give. Blank = no cap.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Optional: first day the coupon can be used.",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Optional: last day the coupon can be used.",
                        null=True,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of redemptions allowed. 0 = unlimited.",
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "max_uses_per_user",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many times one member may redeem this coupon.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="coupon_discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                help_text="Promo coupon applied at checkout (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="memberships.coupon",
            ),
        ),
    ]
