# Generated by Django 5.2.16 on 2026-09-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0015_coupon_membership_coupon_discount_membership_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="show_at_checkout",
            field=models.BooleanField(
                default=True,
                help_text="Show this coupon in the checkout 'Have a coupon?' list. Hidden codes still work when entered manually.",
            ),
        ),
    ]
