# Generated by Django 5.2.16 on 2026-09-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0016_coupon_show_at_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="show_in_marquee",
            field=models.BooleanField(
                default=False,
                help_text="Promote this coupon in the scrolling banner (plan step). Only one coupon is promoted — the earliest matching one wins.",
            ),
        ),
    ]
