# Generated by Django 5.2.16 on 2026-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notificationlog_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="type",
            field=models.CharField(
                choices=[
                    ("confirmation", "Confirmation"),
                    ("renewal", "Renewal"),
                    ("cash_request", "Cash Request"),
                    ("expiry_warning", "Expiry Warning (7 days)"),
                    ("reminder_3day", "Renewal Reminder (3 days)"),
                    ("reminder_1day", "Renewal Reminder (1 day)"),
                ],
                max_length=30,
            ),
        ),
    ]
