# Generated by Django 5.2.17 on 2026-09-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_audit_user_created_idx_accounts_au_user_id_7b1069_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wifi_device_name_2",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
