# Generated by Django 5.2.17 on 2026-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_user_wifi_device_name_2",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="aadhar_document_back",
            field=models.FileField(blank=True, null=True, upload_to="aadhar_docs/"),
        ),
    ]