# Generated by Django 5.2.16 on 2026-09-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_aadhar_document_back"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="delivery_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="send_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
