# Generated by Django 5.2.16 on 2026-09-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_otpcode_delivery_error_otpcode_last_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="promo_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="promo_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
