# Generated by Django 5.2.16 on 2026-09-17 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="ac_ventilation",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("partially", "Partially"), ("no", "No")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="cleanliness",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="focused_study",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("partially", "Partially"), ("no", "No")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="review",
            name="power_backup",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="recommend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("definitely", "Definitely"),
                    ("maybe", "Maybe"),
                    ("no", "No"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="refreshment_area",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("partially", "Partially"), ("no", "No")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="safety",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="separate_seating",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("partially", "Partially"), ("no", "No")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="sports",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
