# Generated by Django 5.2.16 on 2026-09-17 15:05

import apps.complaints.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=apps.complaints.models.generate_reference,
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=60)),
                ("contact", models.CharField(blank=True, default="", max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("seat", "Seat / Booking"),
                            ("ac", "AC / Ventilation"),
                            ("cleanliness", "Cleanliness / Hygiene"),
                            ("power", "Power / Charging"),
                            ("wifi", "Wi-Fi / Internet"),
                            ("staff", "Staff Behaviour"),
                            ("facility", "Facility / Furniture"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["is_resolved", "-created_at"],
                        name="complaints__is_reso_dcd0c3_idx",
                    )
                ],
            },
        ),
    ]
